import{a as L,i as d,S as v}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",b="48410810-6cc12cd8ef8f80f7e97e53d15";async function m(o,t=1){const a={key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await L.get(S,{params:a})).data}catch(s){throw console.error("Image search error:",s),s}}let u;function q(){const o=document.querySelector(".gallery");o.innerHTML=""}function f(o,t,a){const s=document.querySelector(".gallery"),e=document.querySelector(".load-more"),r=document.querySelector(".loader");if(r.style.display="none",e.style.display="none",o.hits.length===0)return d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),!1;const n=o.hits.map(l=>`
    <a href="${l.largeImageURL}" class="gallery-link">
      <div class="gallery-item">
        <img src="${l.webformatURL}" alt="${l.tags}" />
        <div class="image-info">
          <p>Likes: ${l.likes}</p>
          <p>Views: ${l.views}</p>
          <p>Comments: ${l.comments}</p>
          <p>Downloads: ${l.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",n),u&&u.destroy(),u=new v(".gallery a",{captionsData:"alt",captionDelay:250});const y=Math.ceil(o.totalHits/a);return t<y?e.style.display="block":(o.hits.length<a||t>=y)&&(e.style.display="none",d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),!0}function p(){const o=document.querySelector(".loader");o.style.display="block"}function h(){const o=document.querySelector(".loader");o.style.display="none"}let g="",c=1;const i=15;document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".search-form"),t=document.querySelector(".search-input"),a=document.querySelector(".load-more");t.addEventListener("focus",()=>{t.classList.add("pressed")}),t.addEventListener("blur",()=>{t.classList.remove("pressed")}),o.addEventListener("submit",async s=>{s.preventDefault();const e=t.value.trim();if(!e){d.warning({title:"Warning",message:"Please enter a search query"});return}g=e,c=1,q(),p(),a.style.display="none";try{const r=await m(e,c,i);f(r,c,i)&&r.hits.length===i&&(a.style.display="block")}catch(r){console.error("Search error:",r),d.error({title:"Error",message:"Failed to fetch images"})}finally{h(),t.value="",t.classList.remove("pressed")}}),a.addEventListener("click",async()=>{c+=1,p();try{const s=await m(g,c,i);if(f(s,c,i)&&s.hits.length===i){const r=document.querySelector(".gallery-item");if(r){const n=r.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}else a.style.display="none"}catch(s){console.error("Load more error:",s),d.error({title:"Error",message:"Failed to load more images"})}finally{h()}})});
//# sourceMappingURL=index.js.map
