import{a as f,i,S as h}from"./assets/vendor-tnUJPedx.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(r){if(r.ep)return;r.ep=!0;const e=a(r);fetch(r.href,e)}})();const g="https://pixabay.com/api/",L="48410810-6cc12cd8ef8f80f7e97e53d15";async function d(t,s=1){const a={key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s};try{return(await f.get(g,{params:a})).data}catch(o){throw console.error("Image search error:",o),o}}let c;function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function u(t){const s=document.querySelector(".gallery"),a=document.querySelector(".load-more"),o=document.querySelector(".loader");if(o.style.display="none",a.style.display="none",t.hits.length===0)return i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),!1;const r=t.hits.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-link">
      <div class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",r),c&&c.destroy(),c=new h(".gallery a",{captionsData:"alt",captionDelay:250}),t.totalHits>t.hits.length?a.style.display="block":(a.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}function y(){const t=document.querySelector(".loader");t.style.display="block"}function m(){const t=document.querySelector(".loader");t.style.display="none"}let p="",l=1;document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".search-form"),s=document.querySelector(".search-input"),a=document.querySelector(".load-more");s.addEventListener("focus",()=>{s.classList.add("pressed")}),s.addEventListener("blur",()=>{s.classList.remove("pressed")}),t.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements.searchInput,e=r.value.trim();if(!e){iziToast.warning({title:"Warning",message:"Please enter a search query"});return}p=e,l=1,v(),y(),a.style.display="none";try{const n=await d(e,l);u(n)&&(a.style.display="block")}catch(n){console.error("Search error:",n),iziToast.error({title:"Error",message:"Failed to fetch images"})}finally{m(),r.value="",r.classList.remove("pressed")}}),a.addEventListener("click",async()=>{l+=1,y();try{const o=await d(p,l);if(u(o)){const e=document.querySelector(".gallery-item");if(e){const n=e.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}}catch(o){console.error("Load more error:",o),iziToast.error({title:"Error",message:"Failed to load more images"})}finally{m()}})});
//# sourceMappingURL=index.js.map
