import{a as p,i as c,S as h}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(r){if(r.ep)return;r.ep=!0;const e=a(r);fetch(r.href,e)}})();const g="https://pixabay.com/api/",L="48410810-6cc12cd8ef8f80f7e97e53d15";async function d(t,o=1){const a={key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await p.get(g,{params:a})).data}catch(s){throw console.error("Image search error:",s),s}}let l;function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function u(t){const o=document.querySelector(".gallery"),a=document.querySelector(".load-more"),s=document.querySelector(".loader-container");if(s.style.display="none",a.style.display="none",t.hits.length===0)return c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),!1;const r=t.hits.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-link">
      <div class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",r),l&&l.destroy(),l=new h(".gallery a",{captionsData:"alt",captionDelay:250}),t.totalHits>t.hits.length?a.style.display="block":(a.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}function y(){const t=document.querySelector(".loader-container");t.style.display="block"}function m(){const t=document.querySelector(".loader-container");t.style.display="none"}let f="",i=1;document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".search-form"),o=document.querySelector(".search-input"),a=document.querySelector(".load-more");o.addEventListener("focus",()=>{o.classList.add("pressed")}),o.addEventListener("blur",()=>{o.classList.remove("pressed")}),t.addEventListener("submit",async s=>{s.preventDefault();const r=o.value.trim();if(!r){iziToast.warning({title:"Warning",message:"Please enter a search query"});return}f=r,i=1,v(),y(),a.style.display="none";try{const e=await d(r,i);u(e)&&(a.style.display="block")}catch(e){console.error("Search error:",e),iziToast.error({title:"Error",message:"Failed to fetch images"})}finally{m(),o.value="",o.classList.remove("pressed")}}),a.addEventListener("click",async()=>{i+=1,y();try{const s=await d(f,i);if(u(s)){const e=document.querySelector(".gallery-item");if(e){const n=e.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}}catch(s){console.error("Load more error:",s),iziToast.error({title:"Error",message:"Failed to load more images"})}finally{m()}})});
//# sourceMappingURL=index.js.map
